# Generated by Django 2.2.11 on 2020-03-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('sub_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='Mateus', on_delete=django.db.models.deletion.CASCADE, to='news_app.Author')),
                ('category', models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='news_app.Category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
