# Generated by Django 2.2.11 on 2020-03-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content'], name='news_app_po_content_a31696_idx'),
        ),
    ]
